### PR TITLE
Added ExclusiveObjectLocks option in TouchManager to lock all input on one object.

### PR DESCRIPTION
**Pull request by ManeFunction**
For example you have a map that can rotate, scale etc. and a bunch of buttons. In this case you need a multitouch support for your map but when you scale the map you doesn't want to press any button accidentally. So this option provides that.

### CODE REVIEW

**Comment by valyard** [comment]
Thanks for the contribution!
Similar functionality was indeed needed but I am still not sure what would be the best way to implement it...
(1) Have you considered this approach? https://github.com/TouchScript/TouchScript/blob/master/Source/Assets/TouchScript/Examples/Checkers/Scripts/Exclusive.cs
(2) How do you use this functionality? In the case of map and buttons, when Transform gesture triggers on the map you set it as exclusive, right?
(3) Do you ever need more than 1 exclusive gesture at one moment?

**Comment by ManeFunction** [comment]
1) Additional script is not the solution, 'cause for me (in all my 8 projects) all the objects needs to be with exclusive locks. Even if I have 2 buttons and press (but not release) one of it I don't want the 2nd button to be "pressable" but multitouch is the global option and I still need it on the other scene.
2) Right. The next gestures will be cancelled if it caught by other object.
3) Not the gesture is exclusive but object. If you send another gesture to the same object at the same time it will be recognized as well.
At least I made it as global option, so the user can on/off this logic any time.

**Comment by valyard** [comment]
I see. May I ask in what kinds of projects do you use this functionality?

**Comment by ManeFunction** [comment]
All sorts of games. Strategies, puzzles, match-3. You can search for "Tigrido" in AppStore or GooglePlay and 90% of our games uses TouchScript. Thanks for this awesome tool BTW =)

**Pull request closed without merging**
