### PR TITLE
Added new gesture MultiPointPanGesture

### PR DESCRIPTION
**Pull request by Tyex**
Hi Valentin, first I would like to thank you for your awesome work on TouchScript !

I developped a new gesture for a project i'm working on and I thought it could be useful to someone else.

It allows more control on multiple point gestures, like for example a 2 finger scroll, or a swipe with the hand.

The MultiplePointPanGesture is similar to a SimplePanGesture but it requires a minimum number of touches to be recognized. It also checks the directions in which all the touches are moving. The property "min alignment" defines how similar the directions must be for the gesture to be recognized, ranging from -1 (any direction) to 1 (exact same direction).

multipointpangesture alignmentcheck

I changed the TwoPointTransform2DGestureBase into a MultiPointTransform2DGestureBase, where you can specify the number of touches required for the gesture. The TwoPointTransform2DGestureBase now extends the MultiPointTransform2DGestureBase with the number of points required set to 2, and this modification should have no impact on other components using the TwoPointTransform2DGestureBase.

If you have any suggestion or question about the implementation I would be glad to work on it with you :)

### CODE REVIEW

**Comment by valyard** [comment]
Thanks for detailed explanation even with an image! (8
Can you describe how you used this gesture in your project?

**Comment by Tyex** [comment]
Sure !
I used this gesture in 2 projects.

In the first one I made a camera controller and used the MultiPointPanGesture to rotate the camera around one axis when panned with 2 fingers vertically, as you can experience in google maps for example.

multipointpangesture example1




In the second project I used the MultiPointPanGesture to move a large object when swiped with at least 4 fingers int the same direction. This project was made to demonstrate the capabilities of a large multi-touch screen, involving several people. I had to check if the object was touched and moved by a single person, and not by 4 people touching and panning in different directions.

multipointpangesture example2

**Comment by valyard** [comment]
Hey.
I'm still not sure what to do with the scripts you provided. I appreciate contributions very much but I have a bit different plan for the same functionality in the long run.

**Comment by Tyex** [comment]
Hi Valentin,
Feel free to do whatever you want of my scripts.
I hope it has been inspiring to you in some way, and I will look forward to your solution in the future :)
Keep up the good work !

**Comment by valyard** [comment]
Closing this since similar functionality was added.

**Pull request closed without merging**
