### PR TITLE
Fixed CameraLayer2D to work with Unity4.6 (and up) UI system.

### PR DESCRIPTION
**Pull request by pbosteels**
This is just a small adjustment to CameraLayer2D to make it work with the UI system introduced in Unity 4.6.

### CODE REVIEW

**Comment by valyard** [comment]
Hm.
What exactly are you trying to do? 2D colliders and UI system are completely separate things.

**Comment by pbosteels** [comment]
Currently the CameraLayer2D layer takes into account the sortingOrder property of a SpriteRenderer to work out which sprite gets hit first.
But this doesn’t work when you are working with 2D colliders attached to panels & images of the UI system. They don’t have a SpriteRenderer, so the sortHits function will use the camera distance instead, which is not correct.
I just added some extra lines in the sortHits function to make sure that when you compare 2 UI system objects for sorting, you take into account the ordering in the scene.

To be concrete. we have a scene with a complex hierarchy of UI elements, mostly panels, images & UI Text.
To enable working with gestures on these elements, I attached 2d colliders & gesture components, but that only works consistently with my fix.

**Comment by valyard** [comment]
I am working on a UILayer which uses UI raycasting system. If you are using 2D colliders just to have gestures on UI objects you'd better use UILayer instead. The latest code can be found here: https://github.com/TouchScript/TouchScript/tree/UI

**Comment by valyard** [comment]
Closing this since UILayer was added for UI gestures.

**Pull request closed without merging**
