### PR TITLE
Line 467 Throws "key already exists" exception.

### PR DESCRIPTION
**Pull request by yerek**
Happens when scene is loaded again.
Submited change fixes the issue.

### CODE REVIEW

**Comment by valyard** [comment]
Is this happening when a scene is loaded while a touch is ON the device?

**Comment by yerek** [comment]
It throws mostly when an object on which touch gesture is attached is destroyed and scene is loaded again. Exception was causing touch break for me (on the device) and just error message on the unity editor.
When i applied this change problem dissapear.

**Comment by valyard** [comment]
Alright, I see the problem.
But the solution is wrong. I'll try to figure something out.

**Comment by yerek** [comment]
Ok, could you define why is it wrong ? 
For learning purposes ? :)

**Comment by valyard** [comment]
Well, this kinda fixes the symptoms not the cause.
The broken touches are left in the list making it possible for other bugs to appear.
The right solution would be to figure out when it happens and do something about it.

**Pull request closed without merging**
