### PR TITLE
Fixed the value being unchangeable from infinity when there are multiple inspectors

### LINKED ISSUE #271: Gesture values cannot be modified if there are two inspectors.
Example:
1. Add a new inspector panel, and layout inspectors side by side.
2. Create an empty GameObject.
3. Add LongPressGesture to it.
4. Click "Switch to Advance" button.
5. Check "Limit Movement (cm)" and modify the value from infinity to 123.
6. The value is still infinity. I cant modify it!

TouchScript v9.0, Unity 2017.2.0p2, Windows7

### PR DESCRIPTION
**Pull request by ganaware**
Fix #271

### CODE REVIEW

**Comment by valyard** [comment]
Thanks. But this doesn't fully fix the issue with two inspectors. In fact, there are several issues with non-trivial controls. Check this video: https://www.dropbox.com/s/wk9e7rk8mty9p71/double-inspector-bug.mov?dl=0

**Comment by ganaware** [comment]
There are two different issues:

## Limit Pointers

GestureEditor.cs has two private fields: minPointersFloat and maxPointersFloat.

Two inspectors have each own GestureEditor instance, so these private fields' values are inconsistent each other.

## NullToggleDrawer

The NullToggleDrawer instance is occasionally re-assigned to other property, when the inspector IMGUI layout changed (even when there is only one inspector) .  So, it's field is not reliable.

But we need a reliable expanded field, so I wrote SerializedPropertyUserData to store it.

##

In both cases, values stored in instance fields are causes.

**Comment by valyard** [comment]
I don't think that GC is needed since the whole singleton is destroyed when Unity reloads assemblies anyway. Also, the data is so small so this probably will never be an issue.

Another thing is the drawer only needs to get this shared data once when it is created.

I added these changes in the following branch: https://github.com/TouchScript/TouchScript/tree/PR-272
What do you think?

**Comment by ganaware** [comment]
> I don't think that GC is needed since the whole singleton is destroyed when Unity reloads assemblies anyway. Also, the data is so small so this probably will never be an issue.

I agree. 
> Another thing is the drawer only needs to get this shared data once when it is created.

No.
You must get the shared data every time OnGUI() called.
The null check of data field in the first line of updateExpanded() must be removed.

Because a NullToggleDrawer instance is occasionally re-assigned to other property.
For example, there are two NullToggleDrawer instances named "NTD1" and "NTD2".
1. First time:
    - NTD1 is assigned to "Limit Pointers"
    - NTD2 is assigned to "Require Other Gesture to Fail"
2. After changing the checkbox of "Require Other Gesture to Fail":
   - NTD2 may be assigned to "Limit Pointers"
   - NTD3 (= a new instance) may be assigned to "Require Other Gesture to Fail"
   - NTD1 may be destroyed
   - They are reshuffled. I don't know which instance will be assigned to which property.

That is the reason why NullToggleDrawer's field value is not reliable.

**Comment by valyard** [comment]
> Because a NullToggleDrawer instance is occasionally re-assigned to other property.

Yes, you are indeed correct. I updated this PR with the changes.

**Comment by ganaware** [comment]
They work fine!

**Comment by valyard** [comment]
Merged into develop.

**Pull request closed without merging**
